image: maven:3.9.9-eclipse-temurin-21

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository

stages:
  - test
  - build
  - deploy

# ==========================================
# DEVICE SERVICE
# ==========================================
device_test:
  stage: test
  services:
    - name: postgres:17
      alias: postgres
  variables:
    POSTGRES_PASSWORD: postgres
    SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/devices_db
  script:
    - cd device-service
    - mvn test
  rules:
    - changes:
        - device-service/**/*
        - .gitlab-ci.yml

device_build:
  stage: build
  needs: ["device_test"]
  image: docker:27
  services:
    - name: docker:27-dind
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - cd device-service
    - docker build -t bidcast/device-service .
  rules:
    - changes:
        - device-service/**/*
        - .gitlab-ci.yml

device_deploy:
  stage: deploy
  needs: ["device_build"]
  script:
    - echo "🚀 Desplegando Device Service (Simulado)..."
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - device-service/**/*
        - .gitlab-ci.yml

# ==========================================
# USER SERVICE
# ==========================================
user_test:
  stage: test
  services:
    - name: docker:27-dind 
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2375 
    DOCKER_TLS_CERTDIR: "" 
  script:
    - cd user-service
    - mvn test
  rules:
    - changes:
        - user-service/**/*
        - .gitlab-ci.yml

user_build:
  stage: build
  needs: ["user_test"]
  image: docker:27
  services:
    - name: docker:27-dind
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - cd user-service
    - docker build -t bidcast/user-service .
  rules:
    - changes:
        - user-service/**/*
        - .gitlab-ci.yml

user_deploy:
  stage: deploy
  needs: ["user_build"]
  script:
    - echo "🚀 Desplegando User Service (Simulado)..."
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - user-service/**/*
        - .gitlab-ci.yml

# ==========================================
# ADVERTISEMENT SERVICE
# ==========================================
ad_test:
  stage: test
  services:
    - name: docker:27-dind 
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2375 
    DOCKER_TLS_CERTDIR: "" 
  script:
    - cd advertisement-service
    - mvn test 
  rules:
    - changes:
        - advertisement-service/**/*
        - .gitlab-ci.yml

ad_build:
  stage: build
  needs: ["ad_test"]
  image: docker:27
  services:
    - name: docker:27-dind
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - cd advertisement-service
    - docker build -t bidcast/advertisement-service .
  rules:
    - changes:
        - advertisement-service/**/*
        - .gitlab-ci.yml
        
ad_deploy:
  stage: deploy
  needs: ["ad_build"]
  script:
    - echo "🚀 Desplegando Advertisement Service (Simulado)..."
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - advertisement-service/**/*
        - .gitlab-ci.yml

# ==========================================
# WALLET SERVICE
# ==========================================
wallet_test:
  stage: test
  services:
    - name: docker:27-dind 
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2375 
    DOCKER_TLS_CERTDIR: "" 
  script:
    - cd wallet-service
    - mvn test 
  rules:
    - changes:
        - wallet-service/**/*
        - .gitlab-ci.yml

wallet_build:
  stage: build
  needs: ["wallet_test"]
  image: docker:27
  services:
    - name: docker:27-dind
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - cd wallet-service
    - docker build -t bidcast/wallet-service .
  rules:
    - changes:
        - wallet-service/**/*
        - .gitlab-ci.yml
        
wallet_deploy:
  stage: deploy
  needs: ["wallet_build"]
  script:
    - echo "🚀 Desplegando Wallet Service (Simulado)..."
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - wallet-service/**/*
        - .gitlab-ci.yml

# ==========================================
# AUCTION SERVICE
# ==========================================
auction_test:
  stage: test
  services:
    - name: docker:27-dind 
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2375 
    DOCKER_TLS_CERTDIR: "" 
  script:
    - cd auction-service
    - mvn test 
  rules:
    - changes:
        - auction-service/**/*
        - .gitlab-ci.yml

auction_build:
  stage: build
  needs: ["auction_test"]
  image: docker:27
  services:
    - name: docker:27-dind
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - cd auction-service
    - docker build -t bidcast/auction-service .
  rules:
    - changes:
        - auction-service/**/*
        - .gitlab-ci.yml
        
auction_deploy:
  stage: deploy
  needs: ["auction_build"]
  script:
    - echo "🚀 Desplegando Auction Service (Simulado)..."
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - auction-service/**/*
        - .gitlab-ci.yml

# ==========================================
# GATEWAY SERVICE
# ==========================================
gateway_build:
  stage: build
  image: docker:27
  services:
    - name: docker:27-dind
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - cd gateway-service
    - docker build -t bidcast/gateway-service .
  rules:
    - changes:
        - gateway-service/**/*
        - .gitlab-ci.yml
        
gateway_deploy:
  stage: deploy
  needs: ["gateway_build"]
  script:
    - echo "🚀 Desplegando Gateway Service (Simulado)..."
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - gateway-service/**/*
        - .gitlab-ci.yml

# ==========================================
# BILLING SERVICE
# ==========================================
billing_test:
  stage: test
  services:
    - name: docker:27-dind 
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2375 
    DOCKER_TLS_CERTDIR: "" 
  script:
    - cd billing-service
    - mvn test 
  rules:
    - changes:
        - billing-service/**/*
        - .gitlab-ci.yml

billing_build:
  stage: build
  needs: ["billing_test"]
  image: docker:27
  services:
    - name: docker:27-dind
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - cd billing-service
    - docker build -t bidcast/billing-service .
  rules:
    - changes:
        - billing-service/**/*
        - .gitlab-ci.yml
        
billing_deploy:
  stage: deploy
  needs: ["billing_build"]
  script:
    - echo "🚀 Desplegando Billing Service (Simulado)..."
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - billing-service/**/*
        - .gitlab-ci.yml