image: maven:3.9.6-eclipse-temurin-21

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository


stages:
  - test
  - build
  - deploy


device_test:
  stage: test
  services:
    - name: postgres:15-alpine
      alias: postgres
  variables:
    POSTGRES_PASSWORD: postgres
    SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/devices_db
  script:
    - echo "🧪 Corriendo tests Device..."
    - cd device-service
    - mvn test
  rules:
    - changes:
        - device-service/**/*

device_build:
  stage: build
  needs: ["device_test"]
  image: docker:24.0.5
  services:
    - name: docker:24.0.5-dind
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - cd device-service
    - docker build -t bidcast/device-service .
  rules:
    - changes:
        - device-service/**/*

device_deploy:
  stage: deploy
  needs: ["device_build"]
  script:
    - echo "🚀 Desplegando Device Service (Simulado)..."
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - device-service/**/*


user_test:
  stage: test
  services:
    - name: docker:24.0.5-dind 
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2375 
    DOCKER_TLS_CERTDIR: "" 
  script:
    - echo "🧪 Corriendo tests User con Testcontainers..."
    - cd user-service
    - mvn test
  rules:
    - changes:
        - user-service/**/*

user_build:
  stage: build
  needs: ["user_test"]
  image: docker:24.0.5
  services:
    - name: docker:24.0.5-dind
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - cd user-service
    - docker build -t bidcast/user-service .
  rules:
    - changes:
        - user-service/**/*

user_deploy:
  stage: deploy
  needs: ["user_build"]
  script:
    - echo "🚀 Desplegando User Service (Simulado)..."
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - user-service/**/*


ad_test:
  stage: test
  services:
    - name: docker:24.0.5-dind 
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2375 
    DOCKER_TLS_CERTDIR: ""
  script:
    - echo "🧪 Corriendo tests Advertisement con Testcontainers..."
    - cd advertisement-service
    - mvn test 
  rules:
    - changes:
        - advertisement-service/**/*


ad_build:
  stage: build
  needs: ["ad_test"]
  image: docker:24.0.5
  services:
    - name: docker:24.0.5-dind
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - cd advertisement-service
    - docker build -t bidcast/advertisement-service .
  rules:
    - changes:
        - advertisement-service/**/*
        
ad_deploy:
  stage: deploy
  needs: ["ad_build"]
  script:
    - echo "🚀 Desplegando Advertisement Service (Simulado)..."
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - advertisement-service/**/*