services:
  postgres:
    image: postgres:16-alpine
    container_name: bidcast-postgres
    environment:
      POSTGRES_DB: bidcast
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: bidcast-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  redis:
    image: redis:7-alpine
    container_name: bidcast-redis
    ports:
      - "6379:6379"

  gateway-service:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    container_name: bidcast-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - JWT_SECRET_KEY=2UHjkWZU0VNZZeDuGsBZdmYWk8zBbSodnpk/WhB3zOY=
    depends_on:
      - redis

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: bidcast-user
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - JWT_SECRET_KEY=2UHjkWZU0VNZZeDuGsBZdmYWk8zBbSodnpk/WhB3zOY=
    depends_on:
      - postgres

  wallet-service:
    build:
      context: ./wallet-service
      dockerfile: Dockerfile
    container_name: bidcast-wallet
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - postgres
      - rabbitmq

  auction-service:
    build:
      context: ./auction-service
      dockerfile: Dockerfile
    container_name: bidcast-auction
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - postgres
      - redis
      - rabbitmq

  advertisement-service:
    build:
      context: ./advertisement-service
      dockerfile: Dockerfile
    container_name: bidcast-advertisement
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - postgres

  device-service:
    build:
      context: ./device-service
      dockerfile: Dockerfile
    container_name: bidcast-device
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - postgres
