server.port=8081
spring.application.name=user-service
spring.profiles.active=dev
application.security.jwt.secret-key=${JWT_SECRET_KEY}
application.security.jwt.expiration=${JWT_EXPIRATION_MS:86400000}
