# Cache Distribuido (Redis)
spring.cache.type=redis
spring.cache.redis.time-to-live=600000
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=

spring.application.name=auction-service
spring.profiles.active=dev
server.port=8084
spring.threads.virtual.enabled=true
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/auction_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=30
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.pool-name=AuctionHikariPool

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

bidcast.auction.receipt-secret=${AUCTION_RECEIPT_SECRET}
bidcast.wallet-service.url=http://localhost:8083
