spring.application.name=billing-service
server.port=8086

# --- MERCADO PAGO ---
# En producción, esto debe venir de variables de entorno
mercadopago.access.token=${MP_ACCESS_TOKEN}
mercadopago.back-urls.success=${MP_SUCCESS_URL:http://localhost:3000/billing/success}
mercadopago.back-urls.failure=${MP_FAILURE_URL:http://localhost:3000/billing/failure}
mercadopago.back-urls.pending=${MP_PENDING_URL:http://localhost:3000/billing/pending}
mercadopago.notification-url=${MP_NOTIFICATION_URL:https://bidcast-gateway.loca.lt/api/v1/billing/webhook}
mercadopago.webhook.secret=${MP_WEBHOOK_SECRET}

# --- RABBITMQ ---
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:guest}

# --- POSTGRES ---
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/bidcast}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=update
