services:
  postgres:
    image: postgres:15-alpine
    container_name: bidcast-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bidcast_db
    ports:
      - "5433:5432"
    volumes:
      - bidcast_data:/var/lib/postgresql/data

volumes:
  bidcast_data: